### ISSUE TITLE
Boruszyn dataset

### ISSUE THREAD

**Issue by merkato** [OpenDroneMap/ODMdata#1]
I've added Boruszyn dataset as repository, https://github.com/merkato/odm_boruszyn_kap
But I don't know how to send an pull request for creating odm_data submodule.

**Comment by smathermather** [comment]
I'll work on integrating it today.

**Comment by smathermather** [comment]
Ok done:

https://github.com/OpenDroneMap/odm_data/commit/16b416809dbc5554745a16d7d7d4782dc9917016

https://github.com/OpenDroneMap/odm_data/commit/91cb7f97d3f683861dfaf00278eaadc14c81d35b
