### ISSUE TITLE
Huge sample dataset

### ISSUE THREAD

**Issue by zivillian** [OpenDroneMap/ODMdata#15]
I have a dataset (licensed CC0) with 6340 nadir images from the [Ziegeleipark Mildenberg](https://www.google.de/maps/@53.0313859,13.3062261,582m/data=!3m1!1e3) with a ground resolution of 1-2cm/px and 83% overlap.
The area contains some buildings with high chimneys (30m to 60m), some old excavators, two harbours, forest at the edges and a lot of plain grasland.
To make things more interesting: the lawn was mown during the flight and there were some trains running on the area. The total size of the dataset is ~35GB.

Are you interested, or is this way too large?

**Comment by zivillian** [comment]
Another interesting point is, that we had to capture in 2 different heights: 30m for most of the area and 60m for the south west corner (because of the chimney).

**Comment by smathermather** [comment]
Definitely interested. Can you do a pull request?

**Comment by zivillian** [comment]
do you prefer the undistorted images, or an additional folder with the chessboard images?

**Comment by smathermather** [comment]
I suppose the undistorted images would be preferred.
