### ISSUE TITLE
Github Asset links has changed from what's used in the datasets webpage

### ISSUE THREAD

**Issue by blacklightpy** [OpenDroneMap/ODMdata#28]
At https://www.opendronemap.org/odm/datasets/, the links of the tick and cross marks has changed from https://assets-cdn.github.com/images/icons/emoji/unicode/2714.png and https://assets-cdn.github.com/images/icons/emoji/unicode/2716.png to https://github.githubassets.com/images/icons/emoji/unicode/2714.png and https://github.githubassets.com/images/icons/emoji/unicode/2716.png respectively. Basically the server address for assets has changed. please update the links there.

**Comment by coreysnipes** [comment]
@pierotofy @smathermather I'm not sure how the main .org site incorporates the ODMata table info, but maybe we ought to migrate to inline unicode characters our our own embedded images in both places instead of chasing github assets.

**Comment by pierotofy** [comment]
Fixed! Thanks for the report @blacklightpy 

Yeah I agree, we should probably keep a local copy. If this happens again, we'll go that route.
