### ISSUE TITLE
Issues I've found with each dataset 

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODMdata#3]
Ran using `python-port` commit 3c6071, both with and without `--use-opensfm True` tag using vagrant Ubuntu 14.04 with 9 cores and 12GB RAM
- APT
  - 
- Benchmark
  - Successfully ran using opensfm but the dataset is small and fractured
- boruszyn-kap
  - Texturing error: 

```
Error in OdmTexturing:
/odm/src/opencv/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
```
- Caliterra
  - No errors
- copr
  - Georeferencing failed, even using gcp list "GPS_average.txt" 
    - GPS_average.txt is not a GCP file. 
- glam
  - No GPS or GCP file
- langley
  - Error when meshing: 

```
Vertex count in mesh lower than initially generated mesh, unable to decimate.
Saving mesh to file.
Error in OdmMeshing:
Error when saving mesh to file:
/vagrant_data/odm_data/langley/reconstruction-with-image-size-2400-results/odm_mesh-0000.ply
```
- bellus
  - opensfm: ran successfully, but the point cloud was very sparse and distorted
  - opensfm @ 1600: Ran without error
  - bundler: segmentation fault
- lewis
  - opensfm: same as bellus
  - bundler: distorted product
- rv_nir
  - failed in pmvs code 35072
- pacifica
  - removed most of the images during Bundle2PMVS and RadialUndistort then fails for having residuals too low
- seneca
  - runs successfully

**Comment by coreysnipes** [comment]
@smathermather @dakotabenjamin since this is findings from ~4.5 years ago, I recommend we close this issue.  I have already processed many of the datasets in the current ODMdata list, and I am planning to work through the rest to confirm they at least process without errors and generate a sane map + model.

**Comment by smathermather** [comment]
Yup. I think it is safe to close. :)
