### ISSUE TITLE
WebODM Multispectral Radiometric Calibration 

### ISSUE THREAD

**Issue by Mahrukhagha** [OpenDroneMap/ODMdata#37]
Hey, I am doing research on drone image processing, Can you help me how can I calculate radiometric calibration on WebODM using multispectral image dataset.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
