### ISSUE TITLE
New datasets

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODMdata#9]
We should consider adding more small(ish) datasets. There are some heavy hitters here which are useful, but small, discreet, easy-to-test ones should be here too.

**Comment by merkato** [comment]
Give me a day or two for preview orthophoto ;) 
There are great results with very small dataset, ideally georeferenced on terrain.
https://github.com/merkato/odm_mygla_dataset

**Comment by merkato** [comment]
https://github.com/merkato/odm_sance

Next dataset for testing, with great results of historical fortifications in polish-czech border.

**Comment by smathermather** [comment]
Hey! Excellent! Good looking dataset too.

**Comment by smathermather** [comment]
@merkato -- can you do a pull request on the README?:
https://github.com/OpenDroneMap/odm_data/blob/master/README.md

If not, I can add it.

**Comment by coreysnipes** [comment]
I added mygla to the list in PR #23 
Sance was added earlier, too.  Looks like we have a good number of datasets in the <100 range so I'll close this.
